import React from 'react';
import { CloseIcon, WalletConnectIcon } from './icons';

interface WalletConnectQRModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const WalletConnectQRModal: React.FC<WalletConnectQRModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  // In a real app, a QR code string would be generated by a WalletConnect session.
  // This is a placeholder for the UI.
  const placeholderQrData = 'valifi-wallet-connect-session';

  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex justify-center items-center z-50 p-4 motion-safe:animate-slide-in-fade" onClick={onClose}>
      <div className="bg-slate-800 border border-slate-700 rounded-2xl w-full max-w-sm" onClick={e => e.stopPropagation()}>
        <div className="flex justify-between items-center p-6 border-b border-slate-700">
          <h2 className="text-xl font-bold text-white">WalletConnect</h2>
          <button onClick={onClose} className="text-slate-400 hover:text-white"><CloseIcon className="w-6 h-6"/></button>
        </div>
        <div className="p-6 space-y-4 text-center">
            <p className="text-slate-300">Scan this QR code with a WalletConnect-compatible wallet.</p>
            <div className="bg-white p-4 rounded-lg inline-block relative">
                <div className="absolute inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center">
                    <WalletConnectIcon className="w-24 h-24 text-white/80"/>
                </div>
                <img 
                    src={`https://api.qrserver.com/v1/create-qr-code/?size=256x256&data=${encodeURIComponent(placeholderQrData)}&qzone=1`} 
                    alt="WalletConnect QR Code Placeholder" 
                    className="rounded-md"
                />
            </div>
            <p className="text-sm text-slate-400">Live QR code generation is enabled in production builds.</p>
        </div>
      </div>
    </div>
  );
};

export default WalletConnectQRModal;
